### Import and configs

In [3]:
import json
import glob
import pandas as pd
from pathlib import Path

### Parse all the json

In [ ]:
# Find all the json files
files = glob.glob('../data/api_raw/search/*.json')

# Iterate and parse   
rows = []

for file in files:
    with open(file, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    # Extract category and page from filename
    parts = Path(file).stem.split('_page_')
    
    # if not len == 2 means that another JSON is not from a searched product 
    if len(parts)==2:    
        category = parts[0]
        page     = int(parts[1])
    
        search_results = data.get('search_results', [])
        if not search_results:
            #print(f'No results: {file}')
            continue

        for item in search_results:
            prices = item.get("prices", [])
            price_primary = prices[0].get("value") if len(prices) > 0 else None
            price_rrp     = prices[1].get("value") if len(prices) > 1 else None                

            is_sponsored = item.get('sponsored', False)
                
            rows.append({
                'asin':           item.get('asin'),
                'title':          item.get('title'),
                'rating':         item.get('rating'),
                'review_count':   item.get('ratings_total'),
                'sponsored':      is_sponsored,
                'is_prime':       item.get('is_prime'),
                'search_position':item.get('position'),
                'recent_sales':   item.get('recent_sales'),
                'price_primary':  price_primary,
                'price_rrp':      price_rrp,
                'category':       category,
                'page':           page,
            })
    else:
        print(f"[SKIP] {Path(file).stem}")

df = pd.DataFrame(rows)
df.head(10)

,asin,title,rating,review_count,sponsored,is_prime,search_position,recent_sales,price_primary,price_rrp,category,page
0,B09NXS395V,24K Gold Under Eye Patches - 60 Pack for Puffy...,4.1,14615.0,False,False,1,10K+ bought in past month,9.39,9.99,beauty_personal_care,1
1,B091NJQ29P,Good Molecules Yerba Mate Wake Up Eye Gel - Hy...,4.2,28653.0,False,False,2,60K+ bought in past month,5.97,NaN,beauty_personal_care,1
2,B08Z5X1L1S,Gifts for Women Gift Basket for Women - 10 Pc ...,4.6,2369.0,False,False,3,5K+ bought in past month,34.98,65.00,beauty_personal_care,1
3,B08KT2Z93D,"eos Shea Better Body Lotion Vanilla Cashmere, ...",4.7,65741.0,False,False,4,100K+ bought in past month,9.97,10.99,beauty_personal_care,1
4,B0CMV2DCXT,CHMI Under Eye Patches (50 Pairs) - 24K Gold E...,4.5,1021.0,False,False,5,5K+ bought in past month,9.99,NaN,beauty_personal_care,1
5,B0CTK5ZTNK,"Under Eye Patches, 40 Pairs Eye Mask for Dark ...",4.5,5192.0,False,False,6,10K+ bought in past month,9.99,12.99,beauty_personal_care,1
6,B0CNV5SG4S,"Sleeping lip mask, Nourish & Hydrate Lip Mask ...",4.6,969.0,False,False,7,300+ bought in past month,4.99,6.99,beauty_personal_care,1
7,B0C7W6GW8P,"e.l.f. Squeeze Me Lip Balm, Moisturizing Lip B...",4.5,19260.0,False,False,8,10K+ bought in past month,5.00,NaN,beauty_personal_care,1
8,B0CPCYP629,eos 24H Moisture Travel Body Lotion- Vanilla C...,4.8,3099.0,False,False,9,20K+ bought in past month,3.99,NaN,beauty_personal_care,1
9,B0DMTDN158,The Ordinary Glycolic Acid 7% Exfoliating Tone...,4.7,44753.0,False,False,10,40K+ bought in past month,7.65,9.00,beauty_personal_care,1

### Dataframe of products search, create CSV

In [5]:
df.to_csv('../data/processed/products_search.csv', index=False)
print(f"Saved: {df.shape}")

Saved: (1386, 12)

## Best Products by Total Sales
We need to convert recent_sales to Integer for evaluate with a sort by sales, and collect the top 8 products by each category

### Function to parse recent sales to a number

In [21]:
def parse_recent_sales(value):
    # get the integer value from recent sales
    if not isinstance(value, str):
        return None
    
    value = value.upper()

    if 'K+' in value:
        return int(float(value.split('K+')[0].strip()) *1000)
    elif '+' in value:
        return int(value.split('+')[0].strip())
    else:
        return None

### Applied function to cleanup

In [23]:
df['recent_sales_approx'] = df['recent_sales'].apply(parse_recent_sales)
df.head()

,asin,title,rating,review_count,sponsored,is_prime,search_position,recent_sales,price_primary,price_rrp,category,page,recent_sales_approx
0,B09NXS395V,24K Gold Under Eye Patches - 60 Pack for Puffy...,4.1,14615.0,False,False,1,10K+ bought in past month,9.39,9.99,Beauty Personal Care,1,10000.0
1,B091NJQ29P,Good Molecules Yerba Mate Wake Up Eye Gel - Hy...,4.2,28653.0,False,False,2,60K+ bought in past month,5.97,NaN,Beauty Personal Care,1,60000.0
2,B08Z5X1L1S,Gifts for Women Gift Basket for Women - 10 Pc ...,4.6,2369.0,False,False,3,5K+ bought in past month,34.98,65.00,Beauty Personal Care,1,5000.0
3,B08KT2Z93D,"eos Shea Better Body Lotion Vanilla Cashmere, ...",4.7,65741.0,False,False,4,100K+ bought in past month,9.97,10.99,Beauty Personal Care,1,100000.0
4,B0CMV2DCXT,CHMI Under Eye Patches (50 Pairs) - 24K Gold E...,4.5,1021.0,False,False,5,5K+ bought in past month,9.99,NaN,Beauty Personal Care,1,5000.0

### Top 8 products each category by ASIN

In [ ]:
top_asins = (
    df.dropna(subset=['recent_sales_approx'])
    .sort_values('recent_sales_approx', ascending=False)
    .drop_duplicates(subset='asin')
    .groupby('category')
    .head(8)['asin']
    .tolist()
)

print(f"ASINs to query: {len(top_asins)}")
top_asins
df[df['asin'].isin(top_asins)].sort_values('recent_sales_approx', ascending=False)

ASINs to query: 32

,asin,title,rating,review_count,sponsored,is_prime,search_position,recent_sales,price_primary,price_rrp,category,page,recent_sales_approx
3,B08KT2Z93D,"eos Shea Better Body Lotion Vanilla Cashmere, ...",4.7,65741.0,False,False,4,100K+ bought in past month,9.97,10.99,beauty_personal_care,1,100000.0
32,B09541P9WH,Amazon Basics Double-Tipped Cotton Swabs for P...,4.7,71667.0,False,False,33,100K+ bought in past month,2.84,NaN,beauty_personal_care,1,100000.0
38,B0D8W1YVBX,EQQUALBERRY Vitamin Illuminating Serum | Niaci...,4.4,8033.0,False,False,39,100K+ bought in past month,19.99,24.99,beauty_personal_care,1,100000.0
26,B0DBF65JYY,medicube PDRN Pink Peptide Serum with Salmon D...,4.6,10387.0,False,False,27,80K+ bought in past month,18.90,21.80,beauty_personal_care,1,80000.0
74,B00AHAWWO0,Crest 3D Whitestrips Professional Effects – Te...,4.6,102791.0,False,False,22,80K+ bought in past month,45.99,NaN,beauty_personal_care,2,80000.0
19,B0DPHQRLJC,"eos Cashmere Body Wash – Vanilla Cashmere, Moi...",4.8,14386.0,False,False,20,70K+ bought in past month,9.98,11.99,beauty_personal_care,1,70000.0
1,B091NJQ29P,Good Molecules Yerba Mate Wake Up Eye Gel - Hy...,4.2,28653.0,False,False,2,60K+ bought in past month,5.97,NaN,beauty_personal_care,1,60000.0
342,B0BK2SC18T,GuruNanda Teeth Whitening Strips - 7-Day Treat...,4.4,17686.0,False,False,20,60K+ bought in past month,9.97,NaN,beauty_personal_care,7,60000.0
772,B0113UZJE2,"Etekcity Food Kitchen Scale, Digital Grams and...",4.6,144208.0,False,False,3,50K+ bought in past month,13.99,NaN,home_kitchen,3,50000.0
682,B0CJ1B6D6S,Scrub Daddy Scrub Mommy Sponges - Dish Scrubbe...,4.8,31676.0,False,False,31,30K+ bought in past month,13.99,NaN,home_kitchen,1,30000.0
681,B07PZF3QS3,KitchenAid All Purpose Kitchen Shears with Pro...,4.7,69876.0,False,False,30,30K+ bought in past month,7.99,8.99,home_kitchen,1,30000.0
814,B0CTJGJL2T,"Candle Warmer Lamp with Timer Dimmable, Birthd...",4.7,6999.0,False,False,45,20K+ bought in past month,19.99,32.99,home_kitchen,3,20000.0
790,B07HRCDDL1,"MR.SIGA Microfiber Cleaning Cloth,Pack of 12,S...",4.7,102059.0,False,False,21,20K+ bought in past month,13.99,14.99,home_kitchen,3,20000.0
671,B0C3QZ7SNF,"Cisily Sponge Holder for Kitchen Sink, Sink Ca...",4.6,11683.0,False,False,20,20K+ bought in past month,13.99,19.99,home_kitchen,1,20000.0
666,B0F2TB2MMP,"Extra Large Expandable Silverware Organizer, B...",4.8,3893.0,False,False,15,20K+ bought in past month,6.99,NaN,home_kitchen,1,20000.0
540,B01FWAZEIU,APC UPS 600VA / 330W UPS Battery Backup & Surg...,4.5,28652.0,False,False,11,10K+ bought in past month,83.99,NaN,electronics,4,10000.0
697,B0FLXY2CBC,8 Blade All-in-1 Vegetable Chopper Mandoline S...,4.4,874.0,False,False,46,10K+ bought in past month,16.98,19.99,home_kitchen,1,10000.0
348,B0DGHMNQ5Z,"Apple AirPods 4 Wireless Earbuds, Bluetooth He...",4.5,43623.0,False,False,3,10K+ bought in past month,99.00,129.00,electronics,1,10000.0
593,B0B72DBKVF,"Duracell Coppertop 9V Battery, 6 Count (Pack o...",4.8,6464.0,True,False,17,10K+ bought in past month,25.37,NaN,electronics,6,10000.0
367,B0FC5FJZ9Z,Nintendo Switch 2 + Mario Kart World Bundle,4.7,2815.0,False,False,22,10K+ bought in past month,499.00,NaN,electronics,1,10000.0
720,B0FLXY2CBC,8 Blade All-in-1 Vegetable Chopper Mandoline S...,4.4,874.0,True,False,69,10K+ bought in past month,16.98,19.99,home_kitchen,1,10000.0
361,B0CQMRKRV5,"Amazon Fire TV Stick HD (newest model), free a...",4.7,60956.0,False,False,16,10K+ bought in past month,34.99,NaN,electronics,1,10000.0
501,B0FC6S2R7K,"4K+4K Dash Cam Front and Rear, Free 128GB Card...",4.8,4499.0,False,False,14,10K+ bought in past month,129.99,183.00,electronics,2,10000.0
505,B0FC5FJZ9Z,Nintendo Switch 2 + Mario Kart World Bundle,4.7,2815.0,False,False,18,10K+ bought in past month,499.00,NaN,electronics,2,10000.0
506,B09B2SBHQK,"Amazon Echo Show 5 (newest model), Smart displ...",4.2,65560.0,False,False,19,10K+ bought in past month,89.99,NaN,electronics,2,10000.0
535,B0F43VY6TC,2Pack Multi Charging Cable Cord for Travel Vac...,4.2,2450.0,False,False,6,10K+ bought in past month,15.99,NaN,electronics,4,10000.0
1338,B07HJSHT8P,Franklin Sports Kids Baseball Tee - MLB 2-in-1...,4.4,17947.0,False,False,53,9K+ bought in past month,23.99,49.99,sports_outdoors,6,9000.0
1069,B088H5DWV3,WEERTI Thermal Underwear for Women Long Johns ...,4.5,12643.0,True,False,10,4K+ bought in past month,24.99,39.99,sports_outdoors,2,4000.0
1066,B0009KF59W,"WILSON NCAA Final Four Basketball - 29.5"" and ...",4.7,9178.0,False,False,7,3K+ bought in past month,19.99,26.95,sports_outdoors,2,3000.0
1098,B0CG2LW9RN,"Little Tikes T-Ball Set, Red, 5 Balls, for Tod...",4.8,1536.0,False,False,39,3K+ bought in past month,22.99,NaN,sports_outdoors,2,3000.0
1306,B08JGNRJ8P,"BooTaa 29"" Large Dart Board for Kids, Kids Dar...",4.5,11104.0,False,False,21,3K+ bought in past month,16.99,NaN,sports_outdoors,6,3000.0
1092,B0C9BLDRYS,3-in-1 Baseball Set for Kids 3-5 - Tee Ball St...,4.2,2306.0,False,False,33,2K+ bought in past month,29.99,36.99,sports_outdoors,2,2000.0
1326,B08P286Q26,"Nerf Pro Grip Football, Blue, Classic Foam Bal...",4.7,7896.0,False,False,41,2K+ bought in past month,14.97,NaN,sports_outdoors,6,2000.0
1099,B09GNQD678,Nerf Mini Foam Sports Ball Set - Foam Football...,4.7,994.0,False,False,40,1K+ bought in past month,19.99,29.99,sports_outdoors,2,1000.0

### Saves ASINs in a JSON file

In [ ]:
with open('../data/api_raw/top_asins.json', 'w') as f:
    json.dump(top_asins, f)

print(f"Saved {len(top_asins)} ASINs")

Saved 32 ASINs